[Main]
RealAppId=552500
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLCf=alse

[Misc]
ExtraProtection=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true

[DLC]
737040=Warhammer: Vermintide 2 - Collector's Edition
828790=Warhammer: Vermintide 2 - Shadows Over Bögenhafen
975400=Warhammer: Vermintide 2 - Back to Ubersreik
1033060=Warhammer: Vermintide 2 - Winds of Magic
1196780=Warhammer: Vermintide 2 Cosmetic - Incandescent Brand
1196781=Warhammer: Vermintide 2 Cosmetic - Memento Furioso
1196782=Warhammer: Vermintide 2 Cosmetic - Fulminator's Crown
1196783=Warhammer: Vermintide 2 Cosmetic - The Golden Taurox
1196784=Warhammer: Vermintide 2 Cosmetic - The Anvil of Doom
1196785=Warhammer: Vermintide 2 Cosmetic - The Iron Mohawk
1196786=Warhammer: Vermintide 2 Cosmetic - Trophy of the Gave
1196787=Warhammer: Vermintide 2 Cosmetic - Marienburg Bicorne
1196788=Warhammer: Vermintide 2 Cosmetic - Scour-Sun Helm
1196789=Warhammer: Vermintide 2 Cosmetic - Purist's Stovepipe
1196790=Warhammer: Vermintide 2 Cosmetic - Deathvigil Mask
1196791=Warhammer: Vermintide 2 Cosmetic - Stolen Swine
1196792=Warhammer: Vermintide 2 Cosmetic - Executioner's Helm
1196793=Warhammer: Vermintide 2 Cosmetic - Wildrunner's Helm
1196794=Warhammer: Vermintide 2 Cosmetic - Aspect of Adanhu
1282490=Warhammer: Vermintide 2 Cosmetic - Crown of Purity
1343500=Warhammer: Vermintide 2 - Grail Knight Career
1345990=Warhammer: Vermintide 2 - Grail Knight Cosmetic Upgrade
1443780=Warhammer: Vermintide 2 - Outcast Engineer
1443790=Warhammer: Vermintide 2 - Outcast Engineer Cosmetic Upgrade
1592630=Warhammer: Vermintide 2 - Forgotten Relics Pack
1601550=Warhammer: Vermintide 2 - Chaos Wastes
1629000=Warhammer: Vermintide 2 - Sister of the Thorn
1629010=Warhammer: Vermintide 2 - Sister of the Thorn Cosmetic Upgrade
1782450=Warhammer: Vermintide 2 - Warrior Priest Career
1782451=Warhammer: Vermintide 2 - Warrior Priest Cosmetic Upgrade
2199500=Warhammer: Vermintide 2 - A Treacherous Adventure

[Hashes]
0=194772fb4e9136505b6ec1e1df41ee5732a0eb81204bc197f33c08891061ce15e9628669f999691983ab489e9355c81399d47e30764f6a22a88f5b78fc0d6809
