#NoTrayIcon
Do
Sleep(1000)
Until WinExists("COD MWR HOST")
Sleep(20000)
ControlSend("COD MWR HOST", "", 0, "unlockstats")
ControlSend("COD MWR HOST", "", 0, "{ENTER}")
ControlSend("COD MWR HOST", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR HOST", "", 0, "{ENTER}")
ControlSend("COD MWR HOST", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR HOST", "", 0, "{ENTER}")
ControlSend("COD MWR HOST", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR HOST", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P2")
Sleep(20000)
ControlSend("COD MWR P2", "", 0, "unlockstats")
ControlSend("COD MWR P2", "", 0, "{ENTER}")
ControlSend("COD MWR P2", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P2", "", 0, "{ENTER}")
ControlSend("COD MWR P2", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P2", "", 0, "{ENTER}")
ControlSend("COD MWR P2", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P2", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P3")
Sleep(20000)
ControlSend("COD MWR P3", "", 0, "unlockstats")
ControlSend("COD MWR P3", "", 0, "{ENTER}")
ControlSend("COD MWR P3", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P3", "", 0, "{ENTER}")
ControlSend("COD MWR P3", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P3", "", 0, "{ENTER}")
ControlSend("COD MWR P3", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P3", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P4")
Sleep(20000)
ControlSend("COD MWR P4", "", 0, "unlockstats")
ControlSend("COD MWR P4", "", 0, "{ENTER}")
ControlSend("COD MWR P4", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P4", "", 0, "{ENTER}")
ControlSend("COD MWR P4", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P4", "", 0, "{ENTER}")
ControlSend("COD MWR P4", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P4", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P5")
Sleep(20000)
ControlSend("COD MWR P5", "", 0, "unlockstats")
ControlSend("COD MWR P5", "", 0, "{ENTER}")
ControlSend("COD MWR P5", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P5", "", 0, "{ENTER}")
ControlSend("COD MWR P5", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P5", "", 0, "{ENTER}")
ControlSend("COD MWR P5", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P5", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P6")
Sleep(20000)
ControlSend("COD MWR P6", "", 0, "unlockstats")
ControlSend("COD MWR P6", "", 0, "{ENTER}")
ControlSend("COD MWR P6", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P6", "", 0, "{ENTER}")
ControlSend("COD MWR P6", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P6", "", 0, "{ENTER}")
ControlSend("COD MWR P6", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P6", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P7")
Sleep(20000)
ControlSend("COD MWR P7", "", 0, "unlockstats")
ControlSend("COD MWR P7", "", 0, "{ENTER}")
ControlSend("COD MWR P7", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P7", "", 0, "{ENTER}")
ControlSend("COD MWR P7", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P7", "", 0, "{ENTER}")
ControlSend("COD MWR P7", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P7", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("COD MWR P8")
Sleep(20000)
ControlSend("COD MWR P8", "", 0, "unlockstats")
ControlSend("COD MWR P8", "", 0, "{ENTER}")
ControlSend("COD MWR P8", "", 0, "cg_unlockall_loot 1")
ControlSend("COD MWR P8", "", 0, "{ENTER}")
ControlSend("COD MWR P8", "", 0, "cg_unlockall_classes 1")
ControlSend("COD MWR P8", "", 0, "{ENTER}")
ControlSend("COD MWR P8", "", 0, "cg_unlockall_items 1")
ControlSend("COD MWR P8", "", 0, "{ENTER}")