#NoTrayIcon
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")
Do
Sleep(1000)
Until WinExists("Run In Safe Mode?")
Sleep(1000)
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{right}")
ControlSend("Run In Safe Mode?", "", 0, "{ENTER}")